---
abstract: 'Generate X86 assembler code using Perl as a macro pre-processor.'
author:
  - philiprbrenan@gmail.com
build_requires: {}
configure_requires:
  Module::Build: '0.4224'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Nasm-X86
provides:
  Nasm::X86:
    file: lib/Nasm/X86.pm
    version: '20220712'
  Nasm::X86::Variable:
    file: lib/Nasm/X86.pm
requires:
  Carp: '0'
  Data::Dump: '0'
  Data::Table::Text: '20210725'
  Test2::API: '0'
  Test::More: '0'
  Test::Most: '0'
  feature: '0'
resources:
  bugtracker: https://github.com/philiprbrenan/NasmX86/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/philiprbrenan/NasmX86
version: '20220712'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
